name: "Base Modules Recipe"
description: "Install and configure base modules for UBC Web Services websites"
type: "Site"
install:
  # core
  - breakpoint
  - ckeditor5
  - image
  - media
  - media_library
  - responsive_image
  - rest
  - serialization
  # contrib
  - address
  - allowed_formats
  - antibot
  - auto_entitylabel
  - block_exclude_pages
  - chosen
  - ckeditor5_fullscreen
  - config_ignore
  - crop
  - ctools
  - datetime_range
  - datetimehideseconds
  - devel
  - devel_generate
  - dropzonejs
  - editor_advanced_link
  - entity_reference_revisions
  - field_group
  - file_delete
  - focal_point
  - formtips
  - fullcalendar_view
  - google_analytics
  - image_widget_crop
  - jsonapi
  - linkit
  - linkit_media_library
  # - maxlength ##  https://www.drupal.org/project/maxlength/issues/3462158
  - media_alias_display
  - media_bulk_upload
  - media_bulk_upload_dropzonejs
  - media_entity_file_replace
  - menu_block
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - node_revision_delete
  - optional_end_date
  - pathauto
  - paragraphs
  - redirect
  - responsive_table_filter
  - role_delegation
  - scheduler
  - simple_gmap
  - simple_sitemap
  - smtp
  - svg_image
  - telephone
  - text_summary_options
  - token
  - twig_tweak
  - ubc_chosen_style_tweaks
  - ubc_ckeditor_widgets
  - webform
  - webform_ui
